sudo: required

language: go

services:
  - docker

os:
  - linux

go:
  - "1.10"

before_install:
  # Do nothing

script:
  - make build

after_success:
  - make push

branches:
  only:
    - master
